/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ball.java
 *
 * Created on 2009-10-14, 18:20:33
 */

package ball;


/**
 *
 * @author fanzhidong
 */
public class Ball extends javax.swing.JFrame {

    /** Creates new form Ball */
    public Ball() {
        ball=this;//初始化实例
        initComponents();
        initMyComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlAnimation = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        sldV = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sldA = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        sldD = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbV = new javax.swing.JLabel();
        lbA = new javax.swing.JLabel();
        lbD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPos = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbFun = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbVt = new javax.swing.JLabel();
        lbAt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbGrdPos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbMaxH = new javax.swing.JLabel();
        btnPauCon = new javax.swing.JButton();
        chkShowPath = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAnimation.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnimation.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlAnimation.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout pnlAnimationLayout = new javax.swing.GroupLayout(pnlAnimation);
        pnlAnimation.setLayout(pnlAnimationLayout);
        pnlAnimationLayout.setHorizontalGroup(
            pnlAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        pnlAnimationLayout.setVerticalGroup(
            pnlAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        btnOK.setText("观察");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        sldV.setMaximum(17);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lbV, org.jdesktop.beansbinding.ELProperty.create("${text}"), sldV, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sldV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVStateChanged(evt);
            }
        });

        jLabel1.setText("初速度：");

        jLabel2.setText("方向角：");

        sldA.setMaximum(90);
        sldA.setMinimum(-90);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lbA, org.jdesktop.beansbinding.ELProperty.create("${text}"), sldA, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sldA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAStateChanged(evt);
            }
        });

        jLabel3.setText("刷新频率：");

        sldD.setMinimum(1);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lbD, org.jdesktop.beansbinding.ELProperty.create("${text}"), sldD, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        sldD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDStateChanged(evt);
            }
        });

        jLabel4.setText("轨迹方程：");

        jLabel6.setText("质点坐标：");

        lbV.setText("15");

        lbA.setText("60");

        lbD.setText("10");

        jLabel7.setText("m/s");

        jLabel8.setText("°");

        jLabel9.setText("/100 s");

        lbPos.setText("(0 m,0 m)");

        lbFun.setText("y = x^2 -x");

        jLabel10.setText("瞬时速度：");

        lbVt.setText("0 m/s");

        lbAt.setText("0°");

        jLabel12.setText("速度方向角：");

        jLabel15.setText("质点落地点：");

        lbGrdPos.setText("0");

        jLabel13.setText("最大高度：");

        lbMaxH.setText("0");

        btnPauCon.setText("暂停");
        btnPauCon.setEnabled(false);
        btnPauCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauConActionPerformed(evt);
            }
        });

        chkShowPath.setSelected(true);
        chkShowPath.setText("显示路径");
        chkShowPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAt)
                                    .addComponent(lbPos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbVt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sldA, 0, 0, Short.MAX_VALUE)
                                        .addComponent(sldV, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(sldD, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lbV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(lbD)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(273, 273, 273)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbMaxH, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbGrdPos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chkShowPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPauCon)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(sldV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbV)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbA)
                                .addComponent(jLabel8)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(sldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(lbFun))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(lbGrdPos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(lbMaxH))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(lbAt)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbVt)
                                        .addGap(21, 21, 21))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbD)
                                .addComponent(jLabel9)))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkShowPath)
                            .addComponent(btnOK)
                            .addComponent(btnPauCon))))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(this.btnOK.getText().equals(new String("观察")))
        {
            this.btnOK.setText("复位");
            this.btnPauCon.setText("暂停");
            btnPauCon.setEnabled(true);
            animation.setV(new Double(this.lbV.getText()));
            animation.setAlpha(new Double(this.lbA.getText()));
            animation.setDelay(new Double(this.lbD.getText())/100);
            animation.startAnimation();
            //animateThread.start();//运行子线程
        }
        else
        {
            this.btnOK.setText("观察");
            btnPauCon.setText("继续");
            btnPauCon.setEnabled(false);
            animation.stopAnimation();
        }
   
    }//GEN-LAST:event_btnOKActionPerformed

    private void sldVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVStateChanged
        // TODO add your handling code here:
        //System.out.println("a");
        if(animation!=null)
        {
            //this.btnOK.setText("复位");
            animation.setV(new Double(this.lbV.getText()));
            animation.calTraitFun();
            animation.repaint();
            //animation.startAnimation();
        }
    }//GEN-LAST:event_sldVStateChanged

    private void sldAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAStateChanged
        // TODO add your handling code here:
        if(animation!=null)
        {
            //this.btnOK.setText("复位");
            animation.setAlpha(new Double(this.lbA.getText()));
            animation.calTraitFun();
            animation.repaint();
            //animation.startAnimation();
        }
    }//GEN-LAST:event_sldAStateChanged

    private void sldDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDStateChanged
        // TODO add your handling code here:
        if(animation!=null)
        {
            //this.btnOK.setText("复位");
            animation.setDelay(new Double(this.lbD.getText())/100);
            animation.calTraitFun();
            animation.repaint();
            //animation.startAnimation();
        }
    }//GEN-LAST:event_sldDStateChanged

    private void btnPauConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauConActionPerformed
        // TODO add your handling code here:
        if(this.btnPauCon.getText().equals(new String("暂停")))
        {
            animation.pauseAnimation();
            btnPauCon.setText("继续");
        }
        else
        {
            animation.continueAnimation();
            btnPauCon.setText("暂停");
        }
    }//GEN-LAST:event_btnPauConActionPerformed

    private void chkShowPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPathActionPerformed
        // TODO add your handling code here:
        animation.setShowPath(this.chkShowPath.isSelected());
        animation.repaint();
    }//GEN-LAST:event_chkShowPathActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ball().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPauCon;
    private javax.swing.JCheckBox chkShowPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbAt;
    private javax.swing.JLabel lbD;
    private javax.swing.JLabel lbFun;
    private javax.swing.JLabel lbGrdPos;
    private javax.swing.JLabel lbMaxH;
    private javax.swing.JLabel lbPos;
    private javax.swing.JLabel lbV;
    private javax.swing.JLabel lbVt;
    private javax.swing.JPanel pnlAnimation;
    private javax.swing.JSlider sldA;
    private javax.swing.JSlider sldD;
    private javax.swing.JSlider sldV;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private Animation animation;//动画对象
    private AnimateThread animateThread;//动画子线程对象

    private static Ball ball=null;//程序实例
    public static Ball getInstance()//获取程序实例
    {
        return ball;
    }
    private void initMyComponents()//初始化我的组件
    {
               
        //this.setBounds(300, 100, 600, 600);
        //pnlAnimation.setBounds(100,100,500, 500);
        animation=new Animation(getPnlAnimation().getWidth(),getPnlAnimation().getHeight());
        animation.setLocation(0, 0);
        getPnlAnimation().add(animation);

        animation.calTraitFun();
        //animation.startAnimation();
        animateThread =new AnimateThread(animation);

        
       
    }

    /**
     * @return the pnlAnimation
     */
    public javax.swing.JPanel getPnlAnimation() {
        return pnlAnimation;
    }

    /**
     * @return the lbPos
     */
    public javax.swing.JLabel getLbPos() {
        return lbPos;
    }

    /**
     * @return the lbFun
     */
    public javax.swing.JLabel getLbFun() {
        return lbFun;
    }

    /**
     * @return the lbVt
     */
    public javax.swing.JLabel getLbVt() {
        return lbVt;
    }

    /**
     * @return the lbAt
     */
    public javax.swing.JLabel getLbAt() {
        return lbAt;
    }

    /**
     * @return the lbGrdPos
     */
    public javax.swing.JLabel getLbGrdPos() {
        return lbGrdPos;
    }

    /**
     * @return the lbMaxH
     */
    public javax.swing.JLabel getLbMaxH() {
        return lbMaxH;
    }

}
